version: 0.0
os: linux
files:
  - source: /target/SampleMavenTomcatApp.war
    destination: /usr/share/tomcat-codedeploy/webapps/
  - source: /scripts/configure_http_port.xsl
    destination: /usr/share/tomcat-codedeploy/conf/

permissions:
  - object: /usr/share/tomcat-codedeploy/
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/configure_tomcat.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/basic_health_check.sh
      timeout: 300
      runas: root
