version: 0.0
os: linux
files:
  - source: /target/SampleMavenTomcatApp.war
    destination: /opt/tomcat/webapps/

permissions:
  - object: /opt/tomcat/webapps/
    pattern: "**"
    owner: tomcat
    group: tomcat
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_tomcat.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/configure_tomcat.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      timeout: 60
      runas: root
